import type { InteractiveElement } from "../shared/protocol";

const INTERACTIVE_TAGS = new Set(["a", "button", "input", "select", "textarea", "label", "summary"]);
const INTERACTIVE_ROLES = new Set([
  "button", "link", "menuitem", "tab", "checkbox", "radio",
  "switch", "option", "combobox", "searchbox", "textbox",
]);

export function isInteractive(el: Element): boolean {
  const tag = el.tagName.toLowerCase();
  if (INTERACTIVE_TAGS.has(tag)) return true;
  if (el.getAttribute("contenteditable") === "true") return true;
  const role = el.getAttribute("role");
  if (role && INTERACTIVE_ROLES.has(role)) return true;
  if (el.hasAttribute("onclick") || el.hasAttribute("tabindex")) return true;
  return false;
}

export function isVisible(el: Element): boolean {
  const htmlEl = el as HTMLElement;
  if (!htmlEl.offsetParent && htmlEl.tagName !== "BODY") {
    const style = getComputedStyle(htmlEl);
    if (style.position !== "fixed") return false;
  }
  const rect = htmlEl.getBoundingClientRect();
  if (rect.width === 0 || rect.height === 0) return false;
  const style = getComputedStyle(htmlEl);
  if (style.visibility === "hidden" || style.display === "none" || style.opacity === "0") return false;
  return true;
}

function textFor(el: Element): string {
  const htmlEl = el as HTMLElement;
  const aria = htmlEl.getAttribute("aria-label");
  if (aria) return aria.trim();
  const title = htmlEl.getAttribute("title");
  if (title) return title.trim();
  if (htmlEl.tagName === "INPUT" || htmlEl.tagName === "TEXTAREA") {
    const input = htmlEl as HTMLInputElement;
    const placeholder = input.placeholder;
    const value = input.value;
    const name = input.name;
    return [placeholder, value, name].filter(Boolean).join(" | ").trim();
  }
  if (htmlEl.tagName === "IMG") {
    return (htmlEl as HTMLImageElement).alt?.trim() ?? "";
  }
  const t = (htmlEl.innerText || htmlEl.textContent || "").trim().replace(/\s+/g, " ");
  return t.slice(0, 120);
}

function cssEscape(s: string): string {
  if (typeof CSS !== "undefined" && (CSS as unknown as { escape?: (s: string) => string }).escape) {
    return (CSS as unknown as { escape: (s: string) => string }).escape(s);
  }
  return s.replace(/([^\w-])/g, "\\$1");
}

/**
 * Detect auto-generated IDs that change between renders (React useId,
 * framework-assigned UIDs, short alphanumeric counters, long hex hashes).
 * These are lethal as selector anchors because the selector works "right
 * now" but is stale by the time a tool uses it.
 */
function isAutoGeneratedId(id: string): boolean {
  if (!id) return true;
  if (id.length <= 3) return true;
  // React useId: :r0:, :abc:, :r1a:
  if (/^:[\w-]+:$/.test(id)) return true;
  // Short letter(s) + digits counter: c74, r123, a1b2, d987
  if (/^[a-z]{1,3}\d+$/i.test(id)) return true;
  // Single-letter prefix with short tail containing digits: e.g. u12abc
  if (id.length <= 8 && /^[a-z]/i.test(id) && /\d/.test(id)) return true;
  // Long hex hash: abc123def456abc123
  if (id.length >= 16 && /^[a-f0-9-]+$/i.test(id)) return true;
  // Framework-prefixed uids
  if (/^(gwt-uid|ng-tns|_ngcontent|ember\d|radix-)/i.test(id)) return true;
  return false;
}

/** Returns sel if it uniquely matches el in the current document, else null. */
function uniqueSelector(el: Element, sel: string): string | null {
  try {
    const matches = document.querySelectorAll(sel);
    if (matches.length === 1 && matches[0] === el) return sel;
  } catch {
    /* invalid selector */
  }
  return null;
}

function attr(el: Element, name: string): string | null {
  const v = el.getAttribute(name);
  return v != null ? v : null;
}

export function buildSelector(el: Element): string {
  const htmlEl = el as HTMLElement;
  const tag = htmlEl.tagName.toLowerCase();

  // 1. data-testid — the gold standard, always stable across re-renders.
  const testid = attr(htmlEl, "data-testid");
  if (testid) {
    const sel = uniqueSelector(htmlEl, `[data-testid="${cssEscape(testid)}"]`);
    if (sel) return sel;
  }

  // 2. name= on form elements
  const name = attr(htmlEl, "name");
  if (
    name &&
    (htmlEl instanceof HTMLInputElement ||
      htmlEl instanceof HTMLTextAreaElement ||
      htmlEl instanceof HTMLSelectElement ||
      htmlEl instanceof HTMLFormElement)
  ) {
    const sel = uniqueSelector(htmlEl, `${tag}[name="${cssEscape(name)}"]`);
    if (sel) return sel;
  }

  // 3. Stable id (not auto-generated)
  if (htmlEl.id && !isAutoGeneratedId(htmlEl.id)) {
    const sel = uniqueSelector(htmlEl, `#${cssEscape(htmlEl.id)}`);
    if (sel) return sel;
  }

  // 4. aria-label + tag
  const aria = attr(htmlEl, "aria-label");
  if (aria && aria.length > 0 && aria.length < 120) {
    const sel = uniqueSelector(htmlEl, `${tag}[aria-label="${cssEscape(aria)}"]`);
    if (sel) return sel;
  }

  // 5. anchor href (skip "#"/javascript: placeholders)
  if (htmlEl instanceof HTMLAnchorElement) {
    const href = htmlEl.getAttribute("href");
    if (href && href !== "#" && !/^javascript:/i.test(href)) {
      const sel = uniqueSelector(htmlEl, `a[href="${cssEscape(href)}"]`);
      if (sel) return sel;
    }
  }

  // 6. input type+value on submit/button inputs
  if (htmlEl instanceof HTMLInputElement) {
    const type = htmlEl.type;
    const value = htmlEl.value;
    if ((type === "submit" || type === "button") && value) {
      const sel = uniqueSelector(
        htmlEl,
        `input[type="${cssEscape(type)}"][value="${cssEscape(value)}"]`
      );
      if (sel) return sel;
    }
  }

  // 7. Structural path, anchored on the nearest stable ancestor we can find.
  const parts: string[] = [];
  let node: Element | null = htmlEl;
  let depth = 0;
  while (node && node !== document.body && depth < 8) {
    const current: Element = node;
    const currentTag = current.tagName.toLowerCase();
    const parent: HTMLElement | null = current.parentElement;
    if (!parent) break;

    const siblings = Array.from(parent.children).filter(
      (c: Element) => c.tagName === current.tagName
    );
    const idx = siblings.indexOf(current) + 1;
    parts.unshift(`${currentTag}:nth-of-type(${idx})`);

    // Prefer stable anchors: data-testid > stable id > (none).
    const curTestid = attr(current, "data-testid");
    if (curTestid) {
      parts[0] = `${currentTag}[data-testid="${cssEscape(curTestid)}"]`;
      return parts.join(" > ");
    }
    const curId = (current as HTMLElement).id;
    if (curId && !isAutoGeneratedId(curId)) {
      parts.unshift(`#${cssEscape(curId)}`);
      return parts.join(" > ");
    }

    node = parent;
    depth++;
  }
  return parts.join(" > ") || tag;
}

export function extractInteractiveElements(options: { max?: number } = {}): InteractiveElement[] {
  const max = options.max ?? 200;
  const results: InteractiveElement[] = [];
  const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_ELEMENT, {
    acceptNode(node) {
      const el = node as Element;
      if (!isInteractive(el)) return NodeFilter.FILTER_SKIP;
      if (!isVisible(el)) return NodeFilter.FILTER_SKIP;
      return NodeFilter.FILTER_ACCEPT;
    },
  });

  let idx = 0;
  while (walker.nextNode() && idx < max) {
    const el = walker.currentNode as Element;
    const htmlEl = el as HTMLElement;
    results.push({
      idx,
      selector: buildSelector(el),
      tag: el.tagName.toLowerCase(),
      role: htmlEl.getAttribute("role") || undefined,
      type: (htmlEl as HTMLInputElement).type || undefined,
      href: (htmlEl as HTMLAnchorElement).href || undefined,
      text: textFor(el),
    });
    idx++;
  }
  return results;
}

export function queryBySelector(selector: string): HTMLElement | null {
  try {
    return document.querySelector(selector) as HTMLElement | null;
  } catch {
    return null;
  }
}

export function searchByRole(role: string): Element[] {
  return Array.from(document.querySelectorAll(`[role="${cssEscape(role)}"]`)).slice(0, 50);
}

export interface FindByTextOptions {
  query: string;
  exact?: boolean;
  tag?: string;
  role?: string;
  interactiveOnly?: boolean;
  limit?: number;
  /**
   * If set, require a word-boundary match (e.g. "create" won't match
   * "recreate"). Defaults to true for short queries (<= 6 chars) and
   * false for longer queries.
   */
  wholeWord?: boolean;
}

export interface TextMatch {
  selector: string;
  tag: string;
  role?: string;
  text: string;
  matchedOn: "text" | "aria-label" | "title" | "placeholder" | "alt" | "value";
  interactive: boolean;
  /** Depth from <body> — useful for the agent to reason about nesting. */
  depth: number;
}

function depthOf(el: Element): number {
  let d = 0;
  let node: Element | null = el;
  while (node && node !== document.body) {
    d++;
    node = node.parentElement;
  }
  return d;
}

/** Direct text of an element — only its own text nodes, not descendants'. */
function directText(el: Element): string {
  let text = "";
  for (const node of el.childNodes) {
    if (node.nodeType === Node.TEXT_NODE) text += node.textContent ?? "";
  }
  return text.trim();
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/** Recursively yield every element under a root, descending into shadow roots. */
function* walkAllElements(root: Element | Document | ShadowRoot): Generator<HTMLElement> {
  const start =
    root instanceof Document ? root.body : (root as Element | ShadowRoot);
  if (!start) return;
  const walker =
    root instanceof Document || root instanceof ShadowRoot
      ? document.createTreeWalker(start, NodeFilter.SHOW_ELEMENT)
      : document.createTreeWalker(start, NodeFilter.SHOW_ELEMENT);
  let cur: Node | null =
    root instanceof Document || root instanceof ShadowRoot
      ? walker.currentNode
      : (walker.currentNode as Element);
  // Include the current node only if it's a real element (not the document)
  if (cur && cur.nodeType === Node.ELEMENT_NODE) {
    const el = cur as HTMLElement;
    if (cur !== start || root instanceof ShadowRoot) yield el;
    if (el.shadowRoot) yield* walkAllElements(el.shadowRoot);
  }
  while ((cur = walker.nextNode())) {
    const el = cur as HTMLElement;
    yield el;
    if (el.shadowRoot) yield* walkAllElements(el.shadowRoot);
  }
}

export function findByText(options: FindByTextOptions): TextMatch[] {
  const {
    query,
    exact = false,
    tag: filterTag,
    role: filterRole,
    interactiveOnly = false,
    limit = 50,
  } = options;
  const needle = query.trim().toLowerCase();
  if (!needle) return [];

  // Default to word-boundary matching for short queries to avoid "create"
  // matching "recreate"/"created"/etc. — callers can override with wholeWord.
  const useWholeWord = options.wholeWord ?? needle.length <= 6;
  const wordBoundary = useWholeWord
    ? new RegExp(`\\b${escapeRegex(needle)}\\b`, "i")
    : null;

  const matches = (s: string | null | undefined): boolean => {
    if (!s) return false;
    const v = s.trim().toLowerCase();
    if (!v) return false;
    if (exact) return v === needle;
    if (wordBoundary) return wordBoundary.test(v);
    return v.includes(needle);
  };

  interface Candidate {
    el: HTMLElement;
    matchedOn: TextMatch["matchedOn"];
    /** True if the element matched on its OWN text/attr (not a descendant's). */
    ownMatch: boolean;
    depth: number;
  }

  const candidates: Candidate[] = [];
  for (const el of walkAllElements(document)) {
    if (!isVisible(el)) continue;
    if (filterTag && el.tagName.toLowerCase() !== filterTag.toLowerCase()) continue;
    if (filterRole && (el.getAttribute("role") ?? "") !== filterRole) continue;
    if (interactiveOnly && !isInteractive(el)) continue;

    const d = depthOf(el);

    // 1) aria-label / title — attribute-level, definitely "own"
    const aria = el.getAttribute("aria-label");
    if (matches(aria)) {
      candidates.push({ el, matchedOn: "aria-label", ownMatch: true, depth: d });
      continue;
    }
    const title = el.getAttribute("title");
    if (matches(title)) {
      candidates.push({ el, matchedOn: "title", ownMatch: true, depth: d });
      continue;
    }

    // 2) form element values
    if (el instanceof HTMLInputElement || el instanceof HTMLTextAreaElement) {
      if (matches(el.placeholder)) {
        candidates.push({ el, matchedOn: "placeholder", ownMatch: true, depth: d });
        continue;
      }
      if (matches(el.value)) {
        candidates.push({ el, matchedOn: "value", ownMatch: true, depth: d });
        continue;
      }
    }
    if (el instanceof HTMLImageElement && matches(el.alt)) {
      candidates.push({ el, matchedOn: "alt", ownMatch: true, depth: d });
      continue;
    }

    // 3) direct text — the element's own text nodes (excludes descendants)
    const dt = directText(el);
    if (dt && matches(dt)) {
      candidates.push({ el, matchedOn: "text", ownMatch: true, depth: d });
      continue;
    }

    // 4) aggregate text — captures wrappers like <button><span>X</span></button>.
    // Use textContent as a fallback when innerText is empty (e.g. elements
    // that layout doesn't render but are still queryable).
    const inner = (el.innerText || el.textContent || "").trim();
    // Generous cap so we don't traverse giant articles; real containers of
    // interest are well under this. Dedupe handles ancestor/descendant later.
    if (inner && inner.length < 2000 && matches(inner)) {
      candidates.push({ el, matchedOn: "text", ownMatch: false, depth: d });
    }
  }

  if (candidates.length === 0) return [];

  // Dedupe ancestor/descendant chains — but only for "aggregate text"
  // matches, because an own-text / aria-label / placeholder match is
  // specific to that element and never redundant with its descendants.
  //
  // Rule for aggregate-text pairs (parent contains child, both matched):
  //   - parent interactive, child non-interactive  → drop child  (keep button)
  //   - parent non-interactive, child interactive  → drop parent (keep button)
  //   - both interactive or both non-interactive   → drop parent (keep deeper)
  const dropped = new Set<HTMLElement>();
  for (const a of candidates) {
    if (a.ownMatch) continue;
    for (const b of candidates) {
      if (a === b) continue;
      if (!a.el.contains(b.el)) continue; // a is ancestor of b
      if (b.ownMatch) {
        // a matched only via aggregate text, b matched on its own — a is
        // almost certainly a redundant wrapper around b.
        dropped.add(a.el);
        break;
      }
      const aInt = isInteractive(a.el);
      const bInt = isInteractive(b.el);
      if (aInt && !bInt) {
        dropped.add(b.el);
      } else {
        dropped.add(a.el);
        break;
      }
    }
  }

  const kept = candidates.filter((c) => !dropped.has(c.el));

  // Rank: interactive first, then by depth (deepest first), preserving
  // relative document order within ranking buckets via stable sort.
  kept.sort((a, b) => {
    const ai = isInteractive(a.el) ? 1 : 0;
    const bi = isInteractive(b.el) ? 1 : 0;
    if (ai !== bi) return bi - ai;
    return b.depth - a.depth;
  });

  return kept.slice(0, limit).map(({ el, matchedOn, depth }) => ({
    selector: buildSelector(el),
    tag: el.tagName.toLowerCase(),
    role: el.getAttribute("role") || undefined,
    text: displayTextFor(el),
    matchedOn,
    interactive: isInteractive(el),
    depth,
  }));
}

function displayTextFor(el: Element): string {
  const htmlEl = el as HTMLElement;
  const aria = htmlEl.getAttribute("aria-label");
  if (aria) return aria.trim().slice(0, 160);
  const title = htmlEl.getAttribute("title");
  if (title) return title.trim().slice(0, 160);
  if (el instanceof HTMLInputElement || el instanceof HTMLTextAreaElement) {
    const parts = [el.placeholder, el.value, el.name].filter(Boolean).join(" | ");
    if (parts) return parts.slice(0, 160);
  }
  if (el instanceof HTMLImageElement) {
    return (el.alt || "").trim().slice(0, 160);
  }
  const t = (htmlEl.innerText || htmlEl.textContent || "").trim().replace(/\s+/g, " ");
  return t.slice(0, 160);
}

export function scrollBy(direction: "up" | "down" | "left" | "right", amount: number): void {
  const delta = Math.max(0, amount);
  switch (direction) {
    case "up": window.scrollBy({ top: -delta, behavior: "smooth" }); break;
    case "down": window.scrollBy({ top: delta, behavior: "smooth" }); break;
    case "left": window.scrollBy({ left: -delta, behavior: "smooth" }); break;
    case "right": window.scrollBy({ left: delta, behavior: "smooth" }); break;
  }
}

export function dispatchClick(el: HTMLElement): void {
  el.scrollIntoView({ behavior: "instant" as ScrollBehavior, block: "center" });
  el.focus?.();
  const init = { bubbles: true, cancelable: true, view: window, button: 0 };
  el.dispatchEvent(new MouseEvent("mousedown", init));
  el.dispatchEvent(new MouseEvent("mouseup", init));
  el.dispatchEvent(new MouseEvent("click", init));
}

export function setInputValue(el: HTMLElement, text: string): void {
  if (el instanceof HTMLInputElement || el instanceof HTMLTextAreaElement) {
    const nativeSetter = Object.getOwnPropertyDescriptor(
      el instanceof HTMLInputElement ? HTMLInputElement.prototype : HTMLTextAreaElement.prototype,
      "value"
    )?.set;
    if (nativeSetter) nativeSetter.call(el, text);
    else el.value = text;
    el.dispatchEvent(new Event("input", { bubbles: true }));
    el.dispatchEvent(new Event("change", { bubbles: true }));
    return;
  }
  if (el.getAttribute("contenteditable") === "true") {
    el.textContent = text;
    el.dispatchEvent(new InputEvent("input", { bubbles: true }));
  }
}

// Keycodes for non-character keys. Character keys fall back to their charCode.
const KEY_CODES: Record<string, number> = {
  Enter: 13,
  Tab: 9,
  Escape: 27,
  Esc: 27,
  Backspace: 8,
  Delete: 46,
  Space: 32,
  " ": 32,
  ArrowLeft: 37,
  ArrowUp: 38,
  ArrowRight: 39,
  ArrowDown: 40,
  Home: 36,
  End: 35,
  PageUp: 33,
  PageDown: 34,
};

function keyToKeyCode(key: string): number {
  if (KEY_CODES[key] != null) return KEY_CODES[key];
  if (key.length === 1) return key.toUpperCase().charCodeAt(0);
  return 0;
}

function keyToCode(key: string): string {
  if (KEY_CODES[key] != null) {
    if (key === " " || key === "Space") return "Space";
    return key; // Enter, Tab, Escape, Arrow*, Home, End, PageUp/Down
  }
  if (key.length === 1) {
    if (/[a-zA-Z]/.test(key)) return `Key${key.toUpperCase()}`;
    if (/[0-9]/.test(key)) return `Digit${key}`;
  }
  return key;
}

function isTextField(el: Element): el is HTMLInputElement | HTMLTextAreaElement {
  if (el instanceof HTMLTextAreaElement) return true;
  if (el instanceof HTMLInputElement) {
    const t = (el.type || "text").toLowerCase();
    return ["text", "search", "url", "tel", "password", "email", "number"].includes(t);
  }
  return false;
}

function writeInputValue(
  el: HTMLInputElement | HTMLTextAreaElement,
  newValue: string,
  inputType: string,
  data?: string
): void {
  const proto =
    el instanceof HTMLInputElement ? HTMLInputElement.prototype : HTMLTextAreaElement.prototype;
  const setter = Object.getOwnPropertyDescriptor(proto, "value")?.set;
  if (setter) setter.call(el, newValue);
  else el.value = newValue;
  el.dispatchEvent(new InputEvent("input", { bubbles: true, inputType, data }));
}

/**
 * Dispatch a keyboard event AND simulate the default action the browser
 * would normally take. Synthetic KeyboardEvents don't trigger defaults
 * (clicks, text insertion, form submission) so we do it ourselves for the
 * cases browser automation actually cares about.
 */
export function pressKeyOn(el: HTMLElement | null, key: string): { ok: boolean; note?: string } {
  const target = el ?? (document.activeElement as HTMLElement) ?? document.body;
  if (!target) return { ok: false, note: "No target element" };

  // Focus the target so listeners like onKeyDown on the active element fire.
  if (typeof target.focus === "function" && target !== document.activeElement) {
    try {
      target.focus();
    } catch {
      /* ignore */
    }
  }

  const keyCode = keyToKeyCode(key);
  const code = keyToCode(key);
  const init: KeyboardEventInit = {
    key,
    code,
    keyCode,
    which: keyCode,
    charCode: key.length === 1 ? key.charCodeAt(0) : 0,
    bubbles: true,
    cancelable: true,
    composed: true,
    view: window,
  } as KeyboardEventInit;

  // keydown first. If a listener calls preventDefault, skip the default action.
  const keydownEvent = new KeyboardEvent("keydown", init);
  const keydownNotPrevented = target.dispatchEvent(keydownEvent);

  // keypress only fires for keys that produce characters (plus Enter historically).
  if (key.length === 1 || key === "Enter") {
    target.dispatchEvent(new KeyboardEvent("keypress", init));
  }

  // Simulate the default action the browser would perform.
  if (keydownNotPrevented) {
    if (key === "Enter") {
      if (isTextField(target)) {
        // Enter in a single-line input normally submits the form.
        target.form?.requestSubmit?.();
      } else if (
        target instanceof HTMLButtonElement ||
        target instanceof HTMLAnchorElement ||
        target.getAttribute("role") === "button" ||
        target.getAttribute("role") === "link"
      ) {
        target.click();
      }
    } else if (key === " " || key === "Space") {
      if (
        target instanceof HTMLButtonElement ||
        target.getAttribute("role") === "button" ||
        target.getAttribute("role") === "checkbox" ||
        (target instanceof HTMLInputElement &&
          ["checkbox", "radio", "button", "submit"].includes(target.type))
      ) {
        target.click();
      } else if (isTextField(target)) {
        writeInputValue(target, target.value + " ", "insertText", " ");
      }
    } else if (key === "Backspace" && isTextField(target)) {
      if (target.value.length > 0) {
        writeInputValue(target, target.value.slice(0, -1), "deleteContentBackward");
      }
    } else if (key === "Delete" && isTextField(target)) {
      // Best-effort: delete from the cursor position if known, else clear.
      const start = target.selectionStart;
      const end = target.selectionEnd;
      if (start != null && end != null && start === end && start < target.value.length) {
        const next = target.value.slice(0, start) + target.value.slice(start + 1);
        writeInputValue(target, next, "deleteContentForward");
      }
    } else if (key.length === 1 && isTextField(target)) {
      writeInputValue(target, target.value + key, "insertText", key);
    }
  }

  target.dispatchEvent(new KeyboardEvent("keyup", init));

  return { ok: true };
}
